#!/bin/sh

THEMES_DIR="/media/internal/.themes"

CURRENT_DIR="${THEMES_DIR}/.org.webosinternals.thememanager-theme"

if [ ! -f ${CURRENT_DIR}/theme.cfg ]; then
  echo "No configuration file! This error should never happen."
  exit 1
fi

if [ -f ${CURRENT_DIR}/unified_diff.patch ] ||
   [ -d ${CURRENT_DIR}/files_replaceable ]
then
  sh /media/cryptofs/apps/usr/bin/ausmt-remove ${CURRENT_DIR} >/dev/null 2>&1

  if [ "${?}" != "0" ]; then
    echo "Removing of current theme failed! Aborting theme updating."

    exit 1
  fi

  rm -f ${CURRENT_DIR}/unified_diff.patch >/dev/null 2>&1

  rm -rf ${CURRENT_DIR}/files_replaceable >/dev/null 2>&1
fi

while read line ; do
  TYPE=`echo ${line} | awk '{print $1}'`

  SOURCE=`echo ${line} | awk '{print $2}'`
  TARGET=`echo ${line} | awk '{print $3}'`

  if [ "${TYPE}" = "files" ]; then
    FILES_DIR="${CURRENT_DIR}/files_replaceable"

    mkdir -p ${FILES_DIR}/`dirname ${TARGET}` >/dev/null 2>&1

    cp ${SOURCE} ${FILES_DIR}${TARGET} >/dev/null 2>&1

    if [ "${?}" != "0" ]; then
      rm -f ${CURRENT_DIR}/unified_diff.patch >/dev/null 2>&1

      rm -rf ${CURRENT_DIR}/files_replaceable >/dev/null 2>&1

      echo "Error in one of the theme files. File '${SOURCE}' does not exist!"

      exit 1
    fi
  elif [ "${TYPE}" = "patch" ]; then
    sed -e /"^diff "/d -e s:"^--- .*":"--- .orig/${TARGET}": \
      -e s:"^+++ .*":"+++ ${TARGET}": ${SOURCE} \
			>> ${CURRENT_DIR}/unified_diff.patch
  fi
done < ${CURRENT_DIR}/theme.cfg

if [ -f ${CURRENT_DIR}/unified_diff.patch ] ||
   [ -d ${CURRENT_DIR}/files_replaceable ]
then
  sh /media/cryptofs/apps/usr/bin/ausmt-install ${CURRENT_DIR} >/dev/null 2>&1

  if [ "${?}" != "0" ]; then
    echo "Installing of current theme failed! Aborting theme updating."

    rm -f ${CURRENT_DIR}/unified_diff.patch >/dev/null 2>&1

    rm -rf ${CURRENT_DIR}/files_replaceable >/dev/null 2>&1

    exit 1
  fi
fi

exit 0

